== Prometheus Alert Manager
*10 MINUTE EXERCISE*

=== Prerequisites
Please complete lab `Application monitoring in OpenShift with Prometheus and Grafana` before continuing.

=== Example Alert Config
----
groups:
- name: example
  rules:
  - alert: HighRequestLatency
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 10m
    labels:
      severity: page
    annotations:
      summary: High request latency
----

.Alert Manger rules brake down
* Rules and be organized into `groups:`.
* `name:` is the name of the alert rule.
* `alert:` is the name of the alert.
* `expr:` is the PromQL expression to evaluate.
* `for:` defines how long alert has returned before they begin to fire.
* `labels:->severity:` defines the severity of the alert.
* `annotations:->summary:` will define the details of the alert that you would like your end user to know about. 


*Switch to infra project*
----
$ oc project {{INFRA_PROJECT}}
----

*Review defined Promethous alert in ConfigMap*
----
$ oc edit prometheus-server-rulefiles-0
----

*Switch back to application project*
----
$ oc project {{COOLSTORE_PROJECT}}
----

*Get inventory endpoint*
----
INVENTORY_ROUTE_HOST=$(oc get routes | grep inventory  | awk '{print $2}')
echo  $INVENTORY_ROUTE_HOST
----

*Verify the metrics endpoint exists*
---- 
$ curl http://${INVENTORY_ROUTE_HOST}/metrics
----

*Trigger alert*
----
siege -c 200 -t 90 -d 3 http://${INVENTORY_ROUTE_HOST}/api/inventory/329299
----

*View alert dashboard via web browser*
----
{{PROMETHEUS_ROUTE_HOST}}/alerts
----

Well done! You are ready for the next lab.
